# Generated by Django 4.2.2 on 2023-06-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('duration', models.DateTimeField(verbose_name='task duration')),
                ('prerequisite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.task')),
            ],
        ),
    ]
