# Generated by Django 4.2.2 on 2023-06-19 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 16, 30, 48, 121458, tzinfo=datetime.timezone.utc), verbose_name='task duration'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='task',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, null=True, to='scheduling.task'),
        ),
    ]
