# Generated by Django 4.2.1 on 2023-06-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_task_description_alter_task_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(verbose_name='task duration'),
        ),
    ]
