# Generated by Django 4.2.1 on 2023-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_task_name_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='task distance grom the beginnig'),
        ),
    ]
