# Generated by Django 4.2.1 on 2023-06-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisite',
            field=models.ManyToManyField(default=[], to='scheduling.task'),
        ),
    ]
